function readVars() {
	wc_mainHL_power = 'GEEK_INIT';
	wc_mainHR_power = 'GEEK_INIT';
	wc_catwalk01_power = 'GEEK_INIT';
	wc_catwalk02_power = 'GEEK_INIT';
	wc_catwalk03_power = 'GEEK_INIT';
	wc_foldbackHL_power = 'GEEK_INIT';
	wc_foldbackHR_power = 'GEEK_INIT';
	bridge_mainLeft_power = 'GEEK_INIT';
	bridge_mainRight_power = 'GEEK_INIT';
	bridge_mainCenter_power = 'GEEK_INIT';
	bridge_foldbackCenter_power = 'GEEK_INIT';
	chapel_mainSide_power = 'GEEK_INIT';
	chapel_mainCenter_power = 'GEEK_INIT';
	chapel_foldbackSide_power = 'GEEK_INIT';
	gym_mainSide_power = 'GEEK_INIT';
	well_mainCenter_power = 'GEEK_INIT';
	rm101A_mainCenter_power = 'GEEK_INIT';
	rm101C_mainCenter_power = 'GEEK_INIT';
	rm102_mainCenter_power = 'GEEK_INIT';
	rm104_mainCenter_power = 'GEEK_INIT';
	rm128_mainCenter_power = 'GEEK_INIT';
	rm212_mainCenter_power = 'GEEK_INIT';
	rm214_mainCenter_power = 'GEEK_INIT';
	rm216_mainCenter_power = 'GEEK_INIT';
	rmRR1_mainCenter_power = 'GEEK_INIT';
	rmXX_mainCenter_power = 'GEEK_INIT';
}
